# Generated by Django 4.0 on 2022-09-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimbus_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='pickup_time',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_datetime',
            field=models.TextField(default=''),
        ),
    ]
