# Generated by Django 4.0 on 2022-09-03 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nimbus_backend', '0002_remove_trip_pickup_time_trip_trip_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.TextField(default='')),
                ('day', models.TextField(default='')),
                ('hour', models.TextField(default='')),
                ('minute', models.TextField(default='')),
                ('month', models.TextField(default='')),
                ('weekday', models.TextField(default='')),
                ('ap', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_datetime',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nimbus_backend.tripdata'),
        ),
    ]
