# Generated by Django 4.0 on 2022-09-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimbus_backend', '0003_tripdata_alter_trip_trip_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='ap',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='day',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='hour',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='minute',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='month',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='weekday',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_datetime',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='TripData',
        ),
    ]
