# Generated by Django 4.0 on 2022-10-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimbus_backend', '0004_trip_ap_trip_day_trip_hour_trip_minute_trip_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender_filter',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='location_filter',
            field=models.JSONField(default=list),
        ),
    ]
