# Generated by Django 4.0 on 2022-11-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimbus_backend', '0005_student_gender_filter_student_location_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cashapp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dorm',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender_filter',
        ),
        migrations.RemoveField(
            model_name='student',
            name='location_filter',
        ),
        migrations.RemoveField(
            model_name='student',
            name='venmo',
        ),
        migrations.AddField(
            model_name='trip',
            name='gender_filter',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='location_filter',
            field=models.JSONField(default=list),
        ),
    ]
