# Generated by Django 4.0 on 2022-12-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimbus_backend', '0006_remove_student_cashapp_remove_student_dorm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='gender_filter',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='location_filter',
        ),
        migrations.AddField(
            model_name='student',
            name='cashapp',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='venmo',
            field=models.TextField(default=''),
        ),
    ]
