# Generated by Django 4.0 on 2022-01-16 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.TextField(default='')),
                ('dorm', models.CharField(choices=[('K', 'Kissam'), ('E', 'EBI'), ('Z', 'Zeppos'), ('Ro', 'Rothschild'), ('Ra', 'Rand'), ('B', 'Branscomb'), ('H', 'Highland'), ('C', 'Commons'), ('V', 'Village')], max_length=1)),
                ('pickup_time', models.DateTimeField(default=datetime.datetime(2022, 1, 16, 14, 46, 14, 1312))),
                ('number_of_bags', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default='')),
                ('dorm', models.CharField(choices=[('K', 'Kissam'), ('E', 'EBI'), ('Z', 'Zeppos'), ('Ro', 'Rothschild'), ('Ra', 'Rand'), ('B', 'Branscomb'), ('H', 'Highland'), ('C', 'Commons'), ('V', 'Village')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.TextField(default='')),
                ('venmo', models.TextField(default='')),
                ('cashapp', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
