# Generated by Django 4.0 on 2022-01-30 23:22

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_nimbus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridesharerequest',
            name='partner_student',
        ),
        migrations.RemoveField(
            model_name='ridesharerequest',
            name='user_student',
        ),
        migrations.AddField(
            model_name='ridesharerequest',
            name='partner_user',
            field=models.ManyToManyField(related_name='partnerstudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ridesharerequest',
            name='user_user',
            field=models.ManyToManyField(related_name='userstudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 30, 17, 22, 13, 99774)),
        ),
    ]
