# Generated by Django 4.0 on 2022-03-20 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_nimbus', '0002_alter_trip_pickup_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridesharerequest',
            name='partner_trip',
        ),
        migrations.AddField(
            model_name='ridesharerequest',
            name='partner_trip',
            field=models.ManyToManyField(to='project_nimbus.Trip'),
        ),
        migrations.RemoveField(
            model_name='ridesharerequest',
            name='user_trip',
        ),
        migrations.AddField(
            model_name='ridesharerequest',
            name='user_trip',
            field=models.ManyToManyField(to='project_nimbus.Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 14, 55, 33, 468342)),
        ),
    ]
