# Generated by Django 4.0 on 2022-01-27 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_nimbus', '0002_alter_trip_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 19, 8, 57, 114991)),
        ),
        migrations.CreateModel(
            name='RideshareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField()),
                ('partner_trip', models.ManyToManyField(to='project_nimbus.Trip')),
                ('user_trip', models.ManyToManyField(to='project_nimbus.Trip')),
            ],
        ),
    ]
