# Generated by Django 4.0 on 2022-01-27 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_nimbus', '0003_alter_trip_pickup_time_ridesharerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ridesharerequest',
            name='partner_trip',
        ),
        migrations.RemoveField(
            model_name='ridesharerequest',
            name='user_trip',
        ),
        migrations.AddField(
            model_name='ridesharerequest',
            name='partner',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ridesharerequest',
            name='user',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 19, 18, 38, 773094)),
        ),
    ]
