# Generated by Django 4.0 on 2022-04-21 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_nimbus', '0005_alter_trip_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharerequest',
            name='partner_trip',
            field=models.ManyToManyField(related_name='p_trip', to='project_nimbus.Trip'),
        ),
        migrations.AlterField(
            model_name='ridesharerequest',
            name='user_trip',
            field=models.ManyToManyField(related_name='u_trip', to='project_nimbus.Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 14, 17, 36, 452902)),
        ),
    ]
