# Generated by Django 4.0 on 2022-04-21 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_nimbus', '0006_alter_ridesharerequest_partner_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 14, 17, 57, 870257)),
        ),
    ]
