# Generated by Django 4.0 on 2022-04-22 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_nimbus', '0008_alter_trip_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 13, 58, 14, 738349)),
        ),
    ]
