# Generated by Django 4.0 on 2022-05-04 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_nimbus', '0009_alter_trip_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='pickup_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 11, 52, 59, 246168)),
        ),
    ]
