# Generated by Django 4.0 on 2022-05-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_nimbus', '0014_alter_trip_pickup_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='RideshareRequest',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
